# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cef97815fa9b699593a8c7aee4e41aad92b53ba1e2098bee504f7d64d4d06e566f858f5fbfb498866a90feb8ee85c1d2f63084c311eabd5d15051bb29299472

test:
  secret_key_base: 52c8a5ca48ed63758003fcc32569f0625a017225c77a03222e76853853060b68b0391e482ff081b6408fa5b0c9bfb0c8f2b768e30bbb532b2fd726fc62416a3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
