SELECT
  [New Product Progress Data].[Product Code],
  [New Product Progress Data].[Product Name],
  [New Product Progress Data].[MATERIAL ID],
  [New Product Progress Data].[Start Date],
  [New Product Progress Data].[Sales Request?],
  [New Product Progress Data].Priority,
  [New Product Progress Data].[EMail Notification?],
  [New Product Progress Data].[Requested By],
  [New Product Progress Data].Customer,
  [New Product Progress Data].[Disc Nature-Duration-Complexity],
  [New Product Progress Data].[Disc Nature-Duration-Complexity YN],
  [New Product Progress Data].[Disc Nature-Duration-Complexity Date],
  [New Product Progress Data].[Disc Consequences of Failure],
  [New Product Progress Data].[Disc Consequences of Failure YN],
  [New Product Progress Data].[Disc Consequences of Failure Date],
  [New Product Progress Data].[TDS MSDS YN],
  [New Product Progress Data].[TDS MSDS Date],
  [New Product Progress Data].[TDS MSDS Com],
  [New Product Progress Data].[Formula YN],
  [New Product Progress Data].[Formula Date],
  [New Product Progress Data].[Formula Com],
  [New Product Progress Data].[Test Proc Rec YN],
  [New Product Progress Data].[Test Proc Rec Date],
  [New Product Progress Data].[Test Proc Rec Com],
  [New Product Progress Data].[Prod Spec YN],
  [New Product Progress Data].[Prod Spec Date],
  [New Product Progress Data].[Prod Spec Com],
  [New Product Progress Data].[Form to Purch Mang YN],
  [New Product Progress Data].[Form to Purch Mang Date],
  [New Product Progress Data].[Form to Purch Mang Com],
  [New Product Progress Data].[Test proc Forw YN],
  [New Product Progress Data].[Test proc Forw Date],
  [New Product Progress Data].[Test proc Forw Com],
  [New Product Progress Data].[OK on Raws YN],
  [New Product Progress Data].[OK on Raws Date],
  [New Product Progress Data].[OK on Raws Com],
  [New Product Progress Data].[Prod Code Entered YN],
  [New Product Progress Data].[Prod Code Entered Date],
  [New Product Progress Data].[Prod Code Entered Com],
  [New Product Progress Data].[MSDS Init YN],
  [New Product Progress Data].[MSDS Init Date],
  [New Product Progress Data].[MSDS Init Com],
  [New Product Progress Data].[Lab Batch YN],
  [New Product Progress Data].[Lab Batch Date],
  [New Product Progress Data].[Lab Batch Com],
  [New Product Progress Data].[QC Tests Entered YN],
  [New Product Progress Data].[QC Tests Entered Date],
  [New Product Progress Data].[QC Tests Entered Com],
  [New Product Progress Data].[Formula Entered YN],
  [New Product Progress Data].[Formula Entered Date],
  [New Product Progress Data].[Formula Entered Com],
  [New Product Progress Data].Comments,
  [New Product Progress Data].Status,
  [New Product Progress Data].[Formula Image],
  [New Product Progress Data].[QC Image],
  [New Product Progress Data].[Other Image],
  [New Product Progress Data].Env_Aspects_YN,
  [New Product Progress Data].Env_Aspects_Date,
  [New Product Progress Data].Env_Aspects_Com,
  [New Product Progress Data].Cust_Req_YN,
  [New Product Progress Data].Cust_Req_Date,
  [New Product Progress Data].Cust_Req_Com,
  [New Product Progress Data].Cust_Specs_YN,
  [New Product Progress Data].Cust_Specs_Date,
  [New Product Progress Data].Cust_Specs_Com,
  [New Product Progress Data].MOC_YN,
  [New Product Progress Data].MOC_Date,
  [New Product Progress Data].MOC_Com,
  [New Product Progress Data].Sr_Mgmt_Rev_YN,
  [New Product Progress Data].Sr_Mgmt_Rev_Date,
  [New Product Progress Data].Sr_Mgmt_Rev_Comment,
  [New Product Progress Data].Sr_Mgmt_Rev_BY,
  [New Product Progress Data].[Sales to Date]
FROM [New Product Progress Data]
LEFT JOIN [New Product Progress Data CleanUP]
  ON [New Product Progress Data].[Product Code] = [New Product Progress Data CleanUP].[Product Code]
WHERE ((([New Product Progress Data CleanUP].[Product Code]) IS NULL));
